
//THIS PAGE NEEDS TO DISPLAY THE USER INFO W/EMAIL, A LINK/BUTTON
// OF SOME SORT TO GET TO THE QUESTIONS PAGE, 
// PUT IT UNDERNEATH THE PROFILE INFORMATION IN THE SAME DI,
// JUST LIKE THE WIREFRAME SHOWS. 
// 2ND DIV CONTAINER NEEDS TO LIST THE SAVED CONDITIONS,
// EACH ONE THAT IS DISPLAYED NEEDS A DELETE BUTTON,
// AND A TEXT THAT SAYS 'ACCESS KEY?' THAT IS ONLY CHECKED
// IF IT'S TRUE. I CAN PROBABLY DO A ::AFTER OR ::BEFORE
// TO DISPLAY THE KEY FOR THE USER
// ALSO, AN EDIT BUTTON FOR THE PROFILE USER'S NAME AND
// EMAIL. I ALSO WANT A BIG CIRCLE WITH EITHER THEIR IMAGE
// TO UPLOAD(YOU SAW THIS IN CLASS FROM STUDENT PRESENTATION),
// OR JUST A BIG LETTER, GRABBED FROM THE FIRST LETTER
// OF THE USER'S NAME.

function Profile() {
    return(
        <>
            <h1>Profile Page(maybe user page??)</h1>
        </>

    )
};

export default Profile;