// THIS PAGE NEEDS THE QUESTIONS FROM THE QUESTIONS TABLE.
// THE RIGHT SIDE OF PAGE WILL HAVE INPUTS FOR EACH ANSWER
// EACH ANSWER WILL ALSO NEED ITS PLACEHOLDER SHOWING
// EACH INPUT NEEDS TO RECORD EACH KEY CHANGE. MAYBE I'LL DO IT
// SO ON 'BLUE' (LOSE FOCUS), THE DATA FOR THAT SPECIFIC ROW WILL
// BE SAVED TO THE CONDITIONS THAT MATCH THE USER'S KEY. 
// THERE WILL PROBABLY BE NO NEED FOR A SUBMIT BUTTON AT THE END
// THEN, I'LL JUST STATE 'YOUR DATA IS AUTOMATICALLY SAVED.' 
// INCLUDE THE NOTE TO ENSURE ANONYMITY.
 
function Questions() {
    return(
        <>
            <h1>Questions Page</h1>
        </>
    )
};


export default Questions;